# Generated by Django 3.0.8 on 2020-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0002_auto_20200709_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='individual',
            field=models.BooleanField(default=False),
        ),
    ]
